MovieRatingSystem/Controllers/UserController.cs
using MovieModel;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieBLL;
using System.Drawing.Drawing2D;
using Vbes.WebControls.Mvc;

namespace MovieRatingSystem.Controllers
{
    public class UserController : Controller
    {
        MovieRatingModel db = new MovieRatingModel();

        public ActionResult Index(int? page)
        {
            if (UserBLL.isAdmin(this))
                return View(db.Users.OrderBy(u => u.ID).ToPagedList(page ?? 1, 10));
            else
                return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public ActionResult Portrait(string backUrl)
        {
            string path = Request.PhysicalApplicationPath + "portrait";
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);
            HttpPostedFileBase file = Request.Files["myfile"];
            string type = Path.GetExtension(file.FileName).ToLower();
            if ((type.Equals(".jpg") || type.Equals(".png") || type.Equals(".jpeg") || type.Equals(".gif")) && file.ContentLength <= 3145728)
            {
                Image img = Image.FromStream(file.InputStream);
                int max = img.Width < img.Height ? img.Width : img.Height;
                int maxPix = 200;//设定最大像素
                string src = "temp" + DateTime.Now.ToString("yyyyMMddHHmmss") + type;
                /*if (max > maxPix)注释此代码，可将大图片变小，小图片变大
                {*/
                    int width, height;
                    width = img.Width;
                    height = img.Height;
                    float scale = ((float)max / (float)maxPix);
                    if (width < height)
                    {
                        width = maxPix;
                        height = (int)(height / scale);
                    }
                    else
                    {
                        height = maxPix;
                        width = (int)(width / scale);
                    }
                    Image newImg = new Bitmap(img, width, height);
                    newImg.Save(path + "\\" + src, img.RawFormat);
                /*}
                else
                    file.SaveAs(path + "\\" + src);*/
                ViewData.Add("imgresouce", "/portrait/" + src);
                Session["tempPath"] = path;
                Session["tempSrc"] = src;
                Session["backUrl"] = backUrl;
                return View();
            }
            else
                return Content(MoviesBLL.AlertAndRedirect(backUrl, "请上传小于3MB的图片文件!"));
        }

        [HttpPost]
        public ActionResult Header()
        {
            Users user = UserBLL.getLoginUser(this);
            if (user == null)
                return RedirectToAction("Login", "Users");
            user = db.Users.Find(user.ID);
            string path = Session["tempPath"].ToString();
            string src = Session["tempSrc"].ToString();
            int x = Convert.ToInt32(Request["x"]);
            int y = Convert.ToInt32(Request["y"]);
            int w = Convert.ToInt32(Request["w"]);
            int h = Convert.ToInt32(Request["h"]);
            string file = user.UserName.ToLower() + DateTime.Now.ToString("yyyyMMddHHmmss") + Path.GetExtension(src);
            if (SaveImage(path + "\\" + src, path + "\\" + file, w, h, x, y))
            {
                string prefix = "/portrait/";
                string old = user.Header;
                user.Header = prefix + file;
                db.Entry<Users>(user).State = System.Data.Entity.EntityState.Modified;
                if (db.SaveChanges() > 0)
                    UserBLL.Login(this, user);
                //删除临时图片
                FileInfo s = new FileInfo(path + "\\" + src);
                if (s.Exists)
                    s.Delete();
                //删除旧的头像
                if (!string.IsNullOrEmpty(old))
                {
                    FileInfo s1 = new FileInfo(path + "\\" + old.Replace(prefix, ""));
                    if (s1.Exists)
                        s1.Delete();
                }
                ViewData.Add("headimage", user.Header);
            }
            Session.Remove("tempPath");
            Session.Remove("tempSrc");
            string backu = Session["backUrl"].ToString();
            Session.Remove("backUrl");
            if (string.IsNullOrEmpty(backu))
                backu = "/";
            return Redirect(backu);
        }

        public ActionResult Setting()
        {
            Users user = UserBLL.getLoginUser(this);
            if (user == null)
                return RedirectToAction("Login", "Home");
            Address add = new Address(user.Address);
            ViewBag.Prov = add.Prov;
            ViewBag.City = add.City;
            ViewBag.Dist = add.Dist;
            return View(user);
        }

        public ActionResult Delete(int id)
        {
            if (!UserBLL.isAdmin(this))
                return RedirectToAction("Login", "Home");
            Users user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Setting(Users user)
        {
            if (user == null)
                return RedirectToAction("Login", "Home");
            Address add = new Address(Request["prov"], Request["city"], Request["dist"]);
            user.Address = add.GetAddress();
            ViewBag.Prov = add.Prov;
            ViewBag.City = add.City;
            ViewBag.Dist = add.Dist;
            db.Entry<Users>(user).State = System.Data.Entity.EntityState.Modified;
            if (db.SaveChanges() > 0)
            {
                UserBLL.Login(this, user);
                ViewBag.Status = "OK";
            }
            else
                ViewBag.Status = "NO";
            return View(user);
        }

        public ActionResult ChangePassword()
        {
            if (!UserBLL.isLogin(this))
                return RedirectToAction("Login", "Home");
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection form)
        {
            Users user = UserBLL.getLoginUser(this);
            if (user != null)
            {
                string old = form["oldpass"];
                string pass1 = form["password"];
                string pass2 = form["password2"];
                if (pass1.Equals(pass2))
                {
                    if (UserBLL.MD5Hash(old).Equals(user.Password))
                    {
                        Users newUser = db.Users.Find(user.ID);
                        newUser.Password = UserBLL.MD5Hash(pass2);
                        db.Entry<Users>(newUser).State = System.Data.Entity.EntityState.Modified;
                        if (db.SaveChanges() > 0)
                        {
                            UserBLL.Login(this, newUser);
                            return Content(MoviesBLL.AlertAndRedirect("/Index", "修改成功"));
                        }
                        else
                            ViewBag.Message = "修改失败";
                    }
                    else
                        ViewBag.Message = "原密码输入不正确";
                }
                else
                    ViewBag.Message = "两次输入的密码不一致";
            }
            return View();
        }

        /// <summary>
        /// 剪裁图像
        /// </summary>
        /// <param name="Img"></param>
        /// <param name="Width"></param>
        /// <param name="Height"></param>
        /// <param name="X"></param>
        /// <param name="Y"></param>
        /// <returns></returns>
        private bool SaveImage(string img, string path, int width, int height, int x, int y)
        {
            try
            {
                using (var OriginalImage = new Bitmap(img))
                {
                    using (var bmp = new Bitmap(width, height, OriginalImage.PixelFormat))
                    {
                        bmp.SetResolution(OriginalImage.HorizontalResolution, OriginalImage.VerticalResolution);
                        using (Graphics Graphic = Graphics.FromImage(bmp))
                        {
                            Graphic.SmoothingMode = SmoothingMode.AntiAlias;
                            Graphic.InterpolationMode = InterpolationMode.HighQualityBicubic;
                            Graphic.PixelOffsetMode = PixelOffsetMode.HighQuality;
                            Graphic.DrawImage(OriginalImage, new Rectangle(0, 0, width, height), x, y, width, height, GraphicsUnit.Pixel);//裁剪图片
                            bmp.Save(path, OriginalImage.RawFormat);
                            return true;
                        }
                    }
                }
            }
            catch (Exception Ex)
            {
                return false;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}

MovieRatingSystem/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieModel;
using MovieBLL;

namespace MovieRatingSystem.Controllers
{
    public class UserInfoController : Controller
    {
        private MovieRatingModel db = new MovieRatingModel();

        public ActionResult Index(int? id)
        {
            if (id != null)
            {
                Users users = db.Users.Find(id);
                if (users != null)
                {
                    Users user = UserBLL.getLoginUser(this);
                    users.Email = UserBLL.showKeys(user != null ? user.Roles == 1 || users.UserName.Equals(user.UserName) ? 1 : 0 : 0, users.Email);
                    return View(users);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(string id)
        {
            if (id != null)
            {
                Users users = db.Users.Where(u => u.UserName == id).FirstOrDefault();
                if (users != null)
                {
                    Users user = UserBLL.getLoginUser(this);
                    users.Email = UserBLL.showKeys(user != null ? user.Roles == 1 || users.UserName.Equals(user.UserName) ? 1 : 0 : 0, users.Email);
                    return View("Index",users);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieRatingSystem/Views/User/ChangePassword.cshtml

@{
    ViewBag.Title = "修改密码";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    <script type="text/javascript">
        function check() {
            var pass1 = document.getElementById("password");
            var pass2 = document.getElementById("password2");
            if (pass1.value != pass2.value)
                pass2.setCustomValidity("两次输入的密码不正确");
            else
                pass2.setCustomValidity("");
        }
    </script>
}
@using (Html.BeginForm("ChangePassword", "User", FormMethod.Post))
{
    <div class="mdui-card mdui-col-md-5" style="margin:20px auto; float:none; padding:8px 16px;">
        <div class="mdui-textfield mdui-textfield-floating-label">
            <label class="mdui-textfield-label">原密码</label>
            <input name="oldpass" class="mdui-textfield-input" type="password" required="required" />
        </div>
        <div class="mdui-textfield mdui-textfield-floating-label">
            <label class="mdui-textfield-label">新密码</label>
            <input id="password" name="password" class="mdui-textfield-input" type="password" required="required" />
        </div>
        <div class="mdui-textfield mdui-textfield-floating-label">
            <label class="mdui-textfield-label">确认密码</label>
            <input id="password2" name="password2" class="mdui-textfield-input" type="password" required="required" onchange="check()" />
        </div>
        <span class="mdui-textfield-error" style="visibility:visible;">@ViewBag.Message</span>
        <p>
            <button class="mdui-btn mdui-color-theme-accent mdui-ripple" type="submit">修改</button>
        </p>
    </div>
}


MovieRatingSystem/Views/User/Index.cshtml
@model IEnumerable<MovieModel.Users>
@using Vbes.WebControls.Mvc
@{
    ViewBag.Title = "用户管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="mdui-table-fluid" style="margin:20px auto;">
    <table class="mdui-table mdui-table-hoverable mdui-typo">
        <thead>
            <tr>
                <th>用户名
                </th>
                <th>用户组
                </th>
                <th>邮箱
                </th>
                <th>性别
                </th>
                <th>昵称
                </th>
                <th>生日
                </th>
                <th>地址
                </th>
                <th>操作</th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr style="white-space:nowrap;">
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @(item.Roles==1?"管理员":"普通用户")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @(item.Gender?"女":"男")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nickname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Birthday)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td style="white-space:nowrap;" valign="middle">
                        @Html.ActionLink("查看", "Index","UserInfo", new { id = item.ID }, null) &nbsp;
                        @if (item.Roles != MovieBLL.UserBLL.Admin) {
                        <a href="javascript:void(0);" onclick="deleteDialog(@item.ID)">删除</a>}
                    </td>
                </tr>
            }
    </table>
    <div class="mdui-typo" style="padding:8px 16px;">
    @Html.Pager((IPagedList)Model, new PagerOptions
    {
        PageIndexParameterName = "page",
        ShowPageIndexBox = false,
        ShowFirstLast = true,
        ShowPrevNext = false
    })
    </div>
</div>
<button class="mdui-fab mdui-color-theme-accent mdui-ripple mdui-fab-fixed" onclick="javascript:location.href='/Sign'"><i class="mdui-icon material-icons">&#xe145;</i></button>
<script type="text/javascript">
    function deleteDialog(id) {
        mdui.dialog({
            title: '删除用户',
            content: '您确定要删除吗？',
            buttons: [{text: '取消'},{text: '删除',
                  onClick: function (inst) {
                      location.href='/User/Delete/'+id
                  }
              }]
        });
    }
</script>

MovieRatingSystem/Views/User/Portrait.cshtml
@{
    ViewBag.Title = "头像设置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}@section head{
    <link href="/css/Jcrop.min.css" rel="stylesheet" />
    <script src="/scripts/Jcrop.min.js"></script>
    <script type="text/javascript">
        function showCoords(c) {
            jQuery('#x').val(Math.round(c.x));
            jQuery('#y').val(Math.round(c.y));
            jQuery('#w').val(Math.round(c.w));
            jQuery('#h').val(Math.round(c.h));
            $('#saveimg').show();
        };
        $(function () {
            $('#imgPort').Jcrop({
                minSize:[100,100],
                maxSize: [500, 500],
                aspectRatio: 1,
                boxWidth: $('#imgPort').width(),
                boxHeight: $('#imgPort').height(),
                onChange: showCoords,
                onSelect: showCoords,
                onRelease: function () {
                    $('#saveimg').hide();
                },
                setSelect:[0,0,100,100]
            });
        });
    </script>
}
<div class="container">
<p>头像设置</p>
<img src="@ViewData["imgresouce"]" id="imgPort" style="@ViewData["imagestyle"]"/>
    @using (Html.BeginForm("Header", "User", FormMethod.Post)) { 
    <input type="hidden" id="x" name="x" />
    <input type="hidden" id="y" name="y" />
    <input type="hidden" id="w" name="w" />
    <input type="hidden" id="h" name="h" />
    <button id="saveimg" type="submit" class="mdui-btn mdui-color-theme-accent mdui-ripple" style="width:100px; display:none; margin:15px 0px 20px 10px;">裁剪并保存</button>
    }
</div>

MovieRatingSystem/Views/User/Setting.cshtml
@model MovieModel.Users
@{
    ViewBag.Title = "账号设置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}@section head{
<link href="/css/datetimepicker.min.css" rel="stylesheet" />
<script src="/scripts/datetimepicker.js"></script>
<script src="/scripts/datetimeres.js"></script>
<script src="/scripts/jquery.cityselect.js"></script>
<script type="text/javascript">
    $(function () {
        $('#birthday').datetimepicker({
            language:  'zh-CN',
            format: 'yyyy-mm-dd',
            weekStart: 0,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2,
            forceParse: 0,
        });
        $("#city").citySelect({ nodata: "none", prov: "@ViewBag.Prov", city: "@ViewBag.City", dist: "@ViewBag.Dist" });
        saved('@ViewBag.Status');
    });
    function saved(status) {
        var msg = "";
        switch (status) {
            case 'OK':
                msg = "修改成功";
                break;
            case 'NO':
                msg = "修改失败";
                break;
        }
        mdui.snackbar({ message: msg, timeout:1000 });
    }
</script>
}
@using (Html.BeginForm("Setting", "User", FormMethod.Post)) {
@Html.HiddenFor(m=>m.ID)
@Html.HiddenFor(m => m.UserName)
@Html.HiddenFor(m=>m.Password)
@Html.HiddenFor(m=>m.Header)
<div class="mdui-card mdui-col-md-5" style="margin:20px auto; float:none; padding:8px 16px;">
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">用户名</label>
        <label class="mdui-col">@Model.UserName</label>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">邮箱</label>
        @Html.HiddenFor(m => m.Email)
        <label class="mdui-col">@Model.Email</label>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">用户组</label>
        @Html.HiddenFor(m=>m.Roles)
        <label class="mdui-col">@(Model.Roles==MovieBLL.UserBLL.Admin?"管理员":"普通用户")</label>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-textfield-label">昵称</label>
        <input name="Nickname" class="mdui-textfield-input" type="text" required="required" value="@Model.Nickname" />
    </div>
    <div class="mdui-textfield">
        <label class="mdui-textfield-label">生日</label>
        <input id="birthday" name="Birthday" class="mdui-textfield-input" type="text" required="required" pattern="^(^(\d{4})(\-|\/|\.)\d{1,2}\3\d{1,2}$)|(^\d{4}-\d{1,2}-\d{1,2}$)$" value="@Model.Birthday" />
    </div>
    <div>
        <label class="mdui-textfield-label">性别</label>
        <label class="mdui-radio">
            <input type="radio" name="Gender" value="False" @(Model.Gender?"":"checked")/>
            <i class="mdui-radio-icon"></i>男
        </label> &nbsp; &nbsp;
        <label class="mdui-radio">
            <input type="radio" name="Gender" value="True" @(Model.Gender?"checked":"")/>
            <i class="mdui-radio-icon"></i>女
        </label>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-textfield-label">地址</label>
        <div id="city" class="mdui-typo">
            <select name="prov" class="prov"></select>
            <select name="city" class="city" style="display:none;"></select>
            <select name="dist" class="dist" style="display:none;"></select>
        </div>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-textfield-label">个性签名：</label>
        <textarea id="signmark" name="Remark" class="mdui-textfield-input">@Model.Remark</textarea>
    </div>
    <span class="mdui-textfield-error" style="visibility:visible;">@ViewBag.Message</span>
    <p>
        <button class="mdui-btn mdui-color-theme-accent mdui-ripple" type="submit">保存</button>
    </p>
</div>
}