MovieRatingSystem/Controllers/PosterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieModel;
using System.IO;
using MovieBLL;
using Vbes.WebControls.Mvc;

namespace MovieRatingSystem.Controllers
{
    public class PosterController : Controller
    {
        private MovieRatingModel db = new MovieRatingModel();

        public ActionResult Index(int? page)
        {
            if (UserBLL.isAdmin(this))
                return View(db.Poster.OrderBy(p => p.ID).ToPagedList(page ?? 1, 10));
            else
                return RedirectToAction("Login", "Home");
        }

        public ActionResult Details(int? id)
        {
            if (!UserBLL.isAdmin(this))
                return RedirectToAction("Login", "Home");
            if (id != null)
            {
                Poster poster = db.Poster.Find(id);
                if (poster != null)
                    return View(poster);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            if (UserBLL.isAdmin(this))
                return View();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(Poster poster)
        {
            if (!UserBLL.isAdmin(this))
                return RedirectToAction("Login", "Home");
            string path = Request.PhysicalApplicationPath + "posters";
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);
            HttpPostedFileBase file = Request.Files["picture"];
            if (file != null)
            {
                string type = Path.GetExtension(file.FileName).ToLower();
                if ((type.Equals(".jpg") || type.Equals(".png") || type.Equals(".jpeg") || type.Equals(".gif")) && file.ContentLength <= 3145728)
                {
                    string name = DateTime.Now.ToString("yyyyMMddHHmmss") + type;
                    file.SaveAs(path + "\\" + name);
                    poster.Picture = "/posters/" + name;
                    poster.CreateBy = UserBLL.getLoginUser(this).UserName;
                    poster.CreateOn = DateTime.Now;
                    if (ModelState.IsValid)
                    {
                        db.Poster.Add(poster);
                        if (db.SaveChanges() > 0)
                            return RedirectToAction("Index");
                        else
                            ViewBag.Message = "创建失败";
                    }
                }
                else
                    ViewBag.Message = "请上传小于3MB的图片文件";
            }
            return View(poster);
        }

        public ActionResult Edit(int? id)
        {
            if (!UserBLL.isAdmin(this))
                return RedirectToAction("Login", "Home");
            if (id != null)
            {
                Poster poster = db.Poster.Find(id);
                if (poster != null)
                    return View(poster);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Poster poster)
        {
            if (!UserBLL.isAdmin(this))
                return RedirectToAction("Login", "Home");
            string path = Request.PhysicalApplicationPath + "posters";
            HttpPostedFileBase file = Request.Files["pictures"];
            if (file != null && file.ContentLength != 0)
            {
                string type = Path.GetExtension(file.FileName).ToLower();
                if ((type.Equals(".jpg") || type.Equals(".png") || type.Equals(".jpeg") || type.Equals(".gif")) && file.ContentLength <= 3145728)
                {
                    string name = DateTime.Now.ToString("yyyyMMddHHmmss") + type;
                    file.SaveAs(path + "\\" + name);
                    poster.Picture = "/posters/" + name;
                }
                else
                {
                    ViewBag.Message = "请上传小于3MB的图片文件";
                    return View(poster);
                }
            }
            if (ModelState.IsValid)
            {
                poster.CreateBy = UserBLL.getLoginUser(this).UserName;
                poster.CreateOn = DateTime.Now;
                db.Entry(poster).State = EntityState.Modified;
                if (db.SaveChanges() > 0)
                    return RedirectToAction("Index");
                else
                    ViewBag.Message = "更新失败";
            }
            return View(poster);
        }
        
        public ActionResult Delete(int id)
        {
            if (!UserBLL.isAdmin(this))
                return RedirectToAction("Login", "Home");
            Poster poster = db.Poster.Find(id);
            db.Poster.Remove(poster);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieRatingSystem/Views/Poster/Create.cshtml
@model MovieModel.Poster

@{
    ViewBag.Title = "新增海报";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
<script type="text/javascript">
    $(function () {
        $("#myFile").on("change", function () {
            var file = this.files[0];
            if (this.files && file) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#imgProd").show();
                    $("#imgProd").attr("src", e.target.result);
                }
                reader.readAsDataURL(file);
            }
        });
    });
</script>    
}
@using (Html.BeginForm("Create", "Poster", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="mdui-card mdui-col-md-5" style="margin:20px auto; padding:8px 16px;">
        <div class="mdui-textfield">
            <label class="mdui-textfield-label">标题</label>
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "mdui-textfield-input" } })
        </div>
        <div class="mdui-textfield">
            <label class="mdui-textfield-label">海报</label>
            <input id="myFile" type="file" name="picture" accept=".jpg,.png,.gif,.jpeg" class="mdui-textfield-input" required="required" style="opacity:0;"/>
            <div class="mdui-divider"></div>
            <img id="imgProd" style="width:100%; display:none;"/>
        </div>
        <div class="mdui-textfield">
            <label class="mdui-textfield-label">链接</label>
            @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "mdui-textfield-input", required = "required" } })
        </div>
        <div class="mdui-list">
            <label class="mdui-list-item mdui-ripple">
                <span class="mdui-list-item-content">启用</span>
                <label class="mdui-switch">
                    <input type="checkbox" name="Valid" value="true" />
                    <i class="mdui-switch-icon"></i>
                </label>
            </label>
        </div>
        <span class="mdui-textfield-error" style="visibility:visible;">@ViewBag.Message</span>
        <p>
            <button type="submit" class="mdui-btn mdui-color-theme-accent mdui-ripple">保存</button>
            <button type="button" class="mdui-btn mdui-color-theme-accent mdui-ripple" onclick="javascript: location.href='/Poster';">取消</button>
        </p>
    </div>
}

MovieRatingSystem/Views/Poster/Details.cshtml
@model MovieModel.Poster

@{
    ViewBag.Title = "查看海报";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="mdui-card mdui-col-md-5" style="margin:20px auto; padding:8px 16px;">
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">标题</label>
        <label class="mdui-col">@Model.Title</label>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">海报</label>
        <img src="@Model.Picture"/>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">链接</label>
        <label class="mdui-col mdui-typo"><a href="@Model.Url">@Model.Url</a></label>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">启用</label>
        <label class="mdui-col">@Html.DisplayFor(model => model.Valid)</label>
    </div>    
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">更新时间</label>
        <label class="mdui-col">@Model.CreateOn</label>
    </div>
    <div class="mdui-textfield">
        <label class="mdui-text-color-theme-accent">操作者</label>
        <label class="mdui-col">@Model.CreateBy</label>
    </div>
    <p>
        <button type="button" class="mdui-btn mdui-color-theme-accent mdui-ripple" onclick="javascript: location.href='/Poster';">返回</button>
    </p>
</div>

MovieRatingSystem/Views/Poster/Edit.cshtml
@model MovieModel.Poster
@{
    ViewBag.Title = "修改海报";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    <script type="text/javascript">
    $(function () {
        $("#myFile").on("change", function () {
            var file = this.files[0];
            if (this.files && file) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#imgProd").show();
                    $("#imgProd").attr("src", e.target.result);
                }
                reader.readAsDataURL(file);
            }
        });
    });
    </script>
}
@using (Html.BeginForm("Edit", "Poster", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="mdui-card mdui-col-md-5" style="margin:20px auto; padding:8px 16px;">
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.CreateBy)
        @Html.HiddenFor(model => model.CreateOn)
        <div class="mdui-textfield">
            <label class="mdui-textfield-label">标题</label>
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "mdui-textfield-input" } })
        </div>
        <div class="mdui-textfield">
            <label class="mdui-textfield-label">海报</label>
            <input id="myFile" type="file" name="pictures" accept=".jpg,.png,.gif,.jpeg" class="mdui-textfield-input" style="opacity:0;" />
            <div class="mdui-divider"></div>
            <img id="imgProd" style="width:100%;" src="@Model.Picture"/>
            @Html.HiddenFor(m => m.Picture)
        </div>
        <div class="mdui-textfield">
            <label class="mdui-textfield-label">链接</label>
            @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "mdui-textfield-input", required = "required" } })
        </div>
        <div class="mdui-list">
            <label class="mdui-list-item mdui-ripple">
                <span class="mdui-list-item-content">启用</span>
                <label class="mdui-switch">
                    <input type="checkbox" name="Valid" value="true" @(Model.Valid?"checked":"")/>
                    <i class="mdui-switch-icon"></i>
                </label>
            </label>
        </div>
        <span class="mdui-textfield-error" style="visibility:visible;">@ViewBag.Message</span>
        <p>
            <button type="submit" class="mdui-btn mdui-color-theme-accent mdui-ripple">保存</button>
            <button type="button" class="mdui-btn mdui-color-theme-accent mdui-ripple" onclick="javascript: history.go(-1);">取消</button>
        </p>
    </div>
}

MovieRatingSystem/Views/Poster/Index.cshtml
@model IEnumerable<MovieModel.Poster>
@using Vbes.WebControls.Mvc
@{
    ViewBag.Title = "海报管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="mdui-table-fluid" style="margin:20px auto;">
    <table class="mdui-table mdui-table-hoverable mdui-typo">
        <thead>
            <tr>
                <th>
                    标题
                </th>
                <th>
                    链接
                </th>
                <th>
                    启用状态
                </th>
                <th>
                    创建时间
                </th>
                <th>
                    创建者
                </th>
                <th>操作</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr style="white-space:nowrap;">
                <td>@Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>@Html.DisplayFor(modelItem => item.Url)
                </td>
                <td>@Html.DisplayFor(modelItem => item.Valid)
                </td>
                <td>@Html.DisplayFor(modelItem => item.CreateOn)
                </td>
                <td>@Html.DisplayFor(modelItem => item.CreateBy)
                </td>
                <td style="white-space:nowrap;" valign="middle">
                    @Html.ActionLink("查看", "Details", new { id = item.ID }) &nbsp;
                    @Html.ActionLink("编辑", "Edit", new { id = item.ID }) &nbsp;
                    <a href="javascript:void(0);" onclick="deleteDialog(@item.ID)">删除</a>
                </td>
            </tr>
        }
    </table>
    <div class="mdui-typo" style="padding:8px 16px;">
        @Html.Pager((IPagedList)Model, new PagerOptions
        {
            PageIndexParameterName = "page",
            ShowPageIndexBox = false,
            ShowFirstLast = true,
            ShowPrevNext = false
        })
    </div>
</div>
<button class="mdui-fab mdui-color-theme-accent mdui-ripple mdui-fab-fixed" onclick="javascript:location.href='/Poster/Create'"><i class="mdui-icon material-icons">&#xe145;</i></button>
<script type="text/javascript">
    function deleteDialog(id) {
        mdui.dialog({
            title: '删除海报',
            content: '您确定要删除吗？',
            buttons: [{text: '取消'},{text: '删除',
                  onClick: function (inst) {
                      location.href='/Poster/Delete/'+id
                  }
              }]
        });
    }
</script>